### PR TITLE
move maps-dashboard plugin to root path

### PR DESCRIPTION
**Pull request by junqiu-lei**
Signed-off-by: Junqiu Lei <junqiu@amazon.com>

### Description
Currently the maps-dashboard plugin is under `src/plugins/maps-dashboard` in this repo, when we need to run plugin with OSD, by default it should be directly under OpenSearch-Dashbaord/plugins/ folder, which can't  be directly used after checking out this repo to local. So it's not handy for development and git version control at local.

After moving the plugin folder to root path of this repo, we can use `git sparse checkout` to check out the subfolder of `maps_dashboards/` to  `OpenSearch-Dashbaord/plugins/`.

example commands like:
```
git init -branch new_branch

git remote add -f origin https://github.com/junqiu-lei/dashboards-maps.git

git config core.sparsecheckout true

echo "maps_dashboards/" >> .git/info/sparse-checkout

git pull origin layers_functions
```
Finally the directory structure should look like this:
```
.
├── OpenSearch-Dashboards
│   └──plugins
│      └── maps_dashboards
```
This PR currently will only merge to new feature develop branch, we can have a discussion to move both this plugin and custom-import-map to root path for consistency.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by martin-gaievski** [comment]
Do we need to do it just for maps dashboards or it's part of larger campaign?

**Comment by peterzhuamazon** [comment]
I wonder if this would break the current build and test.

**Comment by junqiu-lei** [comment]
> 

> Do we need to do it just for maps dashboards or it's part of larger campaign?

It's just for maps dashboard currently

**Comment by junqiu-lei** [comment]
> I wonder if this would break the current build and test.

This PR only contains new unreleased plugin, so there shouldn't have any build and test for it

**Comment by heemin32** [comment]
I would like to see all or nothing here. Having two different folder structures in a single repo makes it confusing.

**Comment by junqiu-lei** [comment]
Ideally if one repo only contain one plugin, then we don't need to have this strategy, like https://github.com/opensearch-project/anomaly-detection-dashboards-plugin, but the dashboards-maps repo have two plugins(one released - `import custom map` and one developing - `maps dashboards`), so we can't directly check out under OSD, this strategy is already used by [dashboard-report](https://github.com/opensearch-project/anomaly-detection-dashboards-plugin). So I am think to make this strategy change before our new plugin release.

**Review by VijayanB — COMMENTED** [review]
LGTM. We can move custom import map similar to this PR in next release. Nevertheless, we will ensure that it works with build process.

**Review by VijayanB — APPROVED** [review]

**Comment by peterzhuamazon** [comment]
> > I wonder if this would break the current build and test.
> 
> This PR only contains new unreleased plugin, so there shouldn't have any build and test for it

It is related:
https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.3.0/opensearch-dashboards-2.3.0.yml#L36

**Comment by peterzhuamazon** [comment]
> > > I wonder if this would break the current build and test.
> > 
> > 
> > It's just for maps dashboard currently
> 
> It is related: https://github.com/opensearch-project/opensearch-build/blob/main/manifests/2.3.0/opensearch-dashboards-2.3.0.yml#L36

After discuss in @junqiu-lei apparently the one in manifest is `custim-import-map`, and the one in this PR is `dashboards maps`.

A bit confusing TBH but it wont impact builds. Sorry for confusion

Thanks.

**Review by heemin32 — APPROVED** [review]

**Pull request merged**
