### PR TITLE
Fix zoom level type error in custom layer

### PR DESCRIPTION
**Pull request by junqiu-lei**
### Description
Fix zoom level type error in custom layer.

### Issues Resolved
Closes https://github.com/opensearch-project/dashboards-maps/issues/604

### Test Demo

https://github.com/opensearch-project/dashboards-maps/assets/90288540/e2913b7f-17b1-4b53-af50-59ab38b7abcc

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by junqiu-lei** [comment]
Cypress test passed on my local, the failure on the CI is unrelated to the PR.

**Comment by VijayanB** [comment]
Can we add unit test?

**Comment by junqiu-lei** [comment]
> Can we add unit test? Please add screenshot / video on how you tested it. Thanks

Sure

**Comment by junqiu-lei** [comment]
> > Can we add unit test? Please add screenshot / video on how you tested it. Thanks
> 
> Sure

Unit tests and test video added.

**Review by VijayanB — APPROVED** [review]

**Review by naveentatikonda — APPROVED** [review]

**Comment by naveentatikonda** [comment]
@junqiu-lei Are we not backporting this to 2.x ?

**Comment by junqiu-lei** [comment]
> @junqiu-lei Are we not backporting this to 2.x ?

Yes

**Pull request merged**
