### PR TITLE
fix build failed due to missing babel plugins

### PR DESCRIPTION
**Pull request by ruanyl**
### Description
Resolved: 
https://github.com/opensearch-project/dashboards-maps/issues/566
https://github.com/opensearch-project/dashboards-maps/issues/569

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by ruanyl** [comment]
This should backport to 2.x

**Comment by ruanyl** [comment]
@VijayanB @junqiu-lei could you take a look at this PR?

**Comment by ryanbogan** [comment]
There is another file that needs to be changed as well for the build to run successfully.  I'll be raising a PR that contains the babel change and fixes other tests that are failing too.

**Comment by ruanyl** [comment]
> There is another file that needs to be changed as well for the build to run successfully. I'll be raising a PR that contains the babel change and fixes other tests that are failing too.

If they are unrelated, let's put them in different PRs, please merge this PR and you could raise another PR for the test fixes.

**Comment by ryanbogan** [comment]
Code change included in https://github.com/opensearch-project/dashboards-maps/pull/572

**Comment by ruanyl** [comment]
Thanks for fixing this, however, I personally think it's generally not a good practice to squash unrelated changes into one commit.

**Pull request closed without merging**
