### PR TITLE
Update existing CI workflow

### PR DESCRIPTION
**Pull request by junqiu-lei**
### Description
Unblock existing CI workflows for both cypress test and unit test and add cypress test cases for new maps.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by vamshin — APPROVED** [review]
LGTM! Thanks

**Comment by navneet1v** [comment]
After fixing the cypress test why the ci is still failing? @junqiu-lei

**Comment by junqiu-lei** [comment]
> After fixing the cypress test why the ci is still failing? @junqiu-lei

I think it's the similar issue previously also have. it will time out to find element. Just tried to increase wait time.

**Comment by junqiu-lei** [comment]
Cypress tests passed at Ubuntu OS:
```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  documentsLayer.spec.js                   01:48        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  geojson_file_upload.spec.js              01:26        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  import_vector_map_tab.spec.js            01:22        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  opensearchMapLayer.spec.js               01:40        1        1        -        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        06:18        5        5        -        -        -  
```

**Review by VijayanB — APPROVED** [review]

**Review by navneet1v — APPROVED** [review]

**Comment by navneet1v** [comment]
@junqiu-lei lets fix the windows platform tests too.

**Comment by junqiu-lei** [comment]
> @junqiu-lei lets fix the windows platform tests too.

Yes

**Pull request merged**
