### PR TITLE
Merge Feature/new-maps branch head to main

### PR DESCRIPTION
**Pull request by junqiu-lei**
Signed-off-by: Junqiu Lei <junqiu@amazon.com>

### Description
Merge Feature/new maps branch head to main after https://github.com/opensearch-project/dashboards-maps/pull/166 merged.

This PR contains:
https://github.com/opensearch-project/dashboards-maps/pull/158
https://github.com/opensearch-project/dashboards-maps/pull/165
https://github.com/opensearch-project/dashboards-maps/pull/154
https://github.com/opensearch-project/dashboards-maps/pull/159
https://github.com/opensearch-project/dashboards-maps/pull/148

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by VijayanB — APPROVED** [review]

**Comment by junqiu-lei** [comment]
The tests failure is unrelated with this PR.

**Review by navneet1v — APPROVED** [review]

**Comment by navneet1v** [comment]
@junqiu-lei as a next steps can we focus on fixing the CI for this plugin?

**Comment by junqiu-lei** [comment]
> @junqiu-lei as a next steps can we focus on fixing the CI for this plugin?

Yes, I'm fixing the existing cypress CI and then add new maps cypress test case to CI.

**Comment by navneet1v** [comment]
Also we should backport these changes to 2.x

**Pull request merged**
