### PR TITLE
Support adding field label to document layer

### PR DESCRIPTION
**Pull request by junqiu-lei**
### Description
This PR mainly allows user to add label by index pattern field to document layer: 

* Integrate index pattern field to maplibre
* Align UX mock and doc

### Demo
image

https://user-images.githubusercontent.com/90288540/224380195-1043e301-506c-4d22-8806-a47dfb368471.mov

### Issues Resolved
https://github.com/opensearch-project/dashboards-maps/issues/321

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by kolchfa-aws** [comment]
Instead of "Enable label", I would use "Show label". Instead of "Label title", I would use "Label text". Instead of "By field", I would use "Field value". Instead of "Add label" in the text field, use "Enter label text"

**Comment by canascar** [comment]
> Instead of "Enable label", I would use "Show label". Instead of "Label title", I would use "Label text". Instead of "By field", I would use "Field value". Instead of "Add label" in the text field, use "Enter label text"

Would it be better to say "Add label" to the checkbox?

**Comment by junqiu-lei** [comment]
Updated the words on UI @kolchfa-aws @canascar 

image
image

**Review by VijayanB — APPROVED** [review]

**Review by kolchfa-aws — APPROVED** [review]
LGTM. Thank you!

**Review by canascar — APPROVED** [review]

**Pull request merged**
